name: "Build Containers on Update"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-config:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.save-output.outputs.package }}
      version: ${{ steps.save-output.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
        
      - name: Run Build Config
        uses: autamus/buildconfig@v0.0.1
        with:
          parsers_loaded: spack
          packages_path: spack/
      
      - name: Save Package Output
        id: save-output
        run: |
          echo "::set-output name=package::$(cat package)"
          echo "::set-output name=version::$(cat version)"


  spack-containerize:
    runs-on: ubuntu-latest
    needs: build-config
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Registry to Spack
        run: |
          for file in spack/*/*; do
            if [ -d "$file" ]; then
                cp -r "$file/" "/opt/spack/var/spack/repos/builtin/packages/"
            fi
          done

      - name: Generate Spack Environment Dockerfile
        run: |
          export PATH=/opt/spack/bin:$PATH
          package=${{needs.build-config.outputs.package}}
          echo "spack:" > spack.yaml
          echo "  specs: [\"$package\"]" >> spack.yaml
          echo "  view: true" >> spack.yaml

          cat spack.yaml
          spack containerize > Dockerfile

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
           
  build-container:
    needs:
      - spack-containerize
      - build-config
    runs-on: ubuntu-latest
    steps:
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}


      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/jiaqiwang969/test_devOps
          tag-sha: true
          tag-edge: false
          tag-latest: true


      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

